### ISSUE TITLE
Remove documentation for deprecated GET contract query parameter

### ISSUE THREAD

**Issue by mok0230** [hashgraph/hedera-docs#81]
### Description

On the [Mirror Node docs](https://docs.hedera.com/guides/docs/mirror-node-api/rest-api#smart-contracts), it lists an accepted query parameter of `contractId` for the `/api/v1/contracts` endpoint, but a request to that endpoint returns a 400:

```bash
$ curl https://testnet.mirrornode.hedera.com/api/v1/contracts?contractId=0.0.34730039
{"_status":{"messages":[{"message":"Invalid parameter: contractid"}]}}
```

It seems like this endpoint is deprecated in favor of `GET /api/v1/contracts/{contractId}`

```bash
$ curl https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.34730039
{
  "admin_key":null,
  "auto_renew_account":null,
  "auto_renew_period":7776000,
  "contract_id":"0.0.34730039",
  ...
}
```

### Steps to reproduce

```bash
$ curl https://testnet.mirrornode.hedera.com/api/v1/contracts?contractId=0.0.34730039
{"_status":{"messages":[{"message":"Invalid parameter: contractid"}]}}
```

### Hedera network

testnet

### Version

*

**Comment by SimiHunjan** [comment]
hi @mok0230 ! I reviewed your ticket and it looks like the query param should be `contract.id` and not `contractid`.

This is an example for a contract query that works:

https://testnet.mirrornode.hedera.com/api/v1/contracts?contract.Id=0.0.34851951

Response: 

```
contracts":[{"admin_key":null,"auto_renew_account":null,"auto_renew_period":7776000,"contract_id":"0.0.34851951","created_timestamp":"1652979009.479393000","deleted":false,"evm_address":"0x000000000000000000000000000000000213cc6f","expiration_timestamp":null,"file_id":"0.0.26562254","max_automatic_token_associations":0,"memo":"memo","obtainer_id":null,"permanent_removal":null,"proxy_account_id":null,"timestamp":{"from":"1652979009.479393000","to":null}}],"links":{"next":null}}
```

I have updated the docs here: https://docs.hedera.com/guides/docs/mirror-node-api/rest-api#smart-contracts.

Thank you for flagging!
